apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-crud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-boot-crud
  template:
    metadata:
      labels:
        app: spring-boot-crud
    spec:
      containers:
        - name: spring-boot-crud
          image: devcode961/spring-boot-crud:latest
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: DB_PORT
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: DB_NAME
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: DB_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: spring-boot-crud-service
spec:
  selector:
    app: spring-boot-crud
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer