CREATE TABLE if not exists product
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name  VARCHAR(255),
    price DOUBLE PRECISION                        NOT NULL,
    CONSTRAINT pk_product PRIMARY KEY (id)
);